### ISSUE TITLE
 能不能把0.13版本的release放一下

### ISSUE THREAD

**Issue by mynameis-GK** [Gaoyongxian666/Douyin_bot#1]
感谢分享 ，昨天还能正常下载 今天全部下载失败  能不能把0.13版本的release放一下  我尝试打包可是没成功 不清楚那个模块漏掉了  或者能告知打包需要安装哪几个模块吗

**Comment by Gaoyongxian666** [comment]
一会儿，我修改一下readme，添加上怎么打包
